// utils/bangladeshLocations.js
export const bangladeshLocations = {
  divisions: [
    { id: "dhaka", name: "Dhaka", value: "dhaka" },
    { id: "chattogram", name: "Chattogram", value: "chattogram" },
    { id: "khulna", name: "Khulna", value: "khulna" },
    { id: "rajshahi", name: "Rajshahi", value: "rajshahi" },
    { id: "barishal", name: "Barishal", value: "barishal" },
    { id: "sylhet", name: "Sylhet", value: "sylhet" },
    { id: "rangpur", name: "Rangpur", value: "rangpur" },
    { id: "mymensingh", name: "Mymensingh", value: "mymensingh" },
  ],

  districts: {
    dhaka: [
      { id: "dhaka", name: "Dhaka", value: "dhaka" },
      { id: "gazipur", name: "Gazipur", value: "gazipur" },
      { id: "narayanganj", name: "Narayanganj", value: "narayanganj" },
      { id: "tangail", name: "Tangail", value: "tangail" },
      { id: "kishoreganj", name: "Kishoreganj", value: "kishoreganj" },
      { id: "manikganj", name: "Manikganj", value: "manikganj" },
      { id: "munshiganj", name: "Munshiganj", value: "munshiganj" },
      { id: "rajbari", name: "Rajbari", value: "rajbari" },
      { id: "shariatpur", name: "Shariatpur", value: "shariatpur" },
      { id: "madaripur", name: "Madaripur", value: "madaripur" },
      { id: "gopalganj", name: "Gopalganj", value: "gopalganj" },
      { id: "faridpur", name: "Faridpur", value: "faridpur" },
    ],
    chattogram: [
      { id: "chattogram", name: "Chattogram", value: "chattogram" },
      { id: "cox-bazar", name: "Cox's Bazar", value: "cox-bazar" },
      { id: "bandarban", name: "Bandarban", value: "bandarban" },
      { id: "rangamati", name: "Rangamati", value: "rangamati" },
      { id: "khagrachari", name: "Khagrachari", value: "khagrachari" },
      { id: "feni", name: "Feni", value: "feni" },
      { id: "comilla", name: "Cumilla", value: "comilla" },
      { id: "noakhali", name: "Noakhali", value: "noakhali" },
      { id: "lakshmipur", name: "Lakshmipur", value: "lakshmipur" },
      { id: "brahmanbaria", name: "Brahmanbaria", value: "brahmanbaria" },
      { id: "chandpur", name: "Chandpur", value: "chandpur" },
    ],
    khulna: [
      { id: "khulna", name: "Khulna", value: "khulna" },
      { id: "bagerhat", name: "Bagerhat", value: "bagerhat" },
      { id: "satkhira", name: "Satkhira", value: "satkhira" },
      { id: "jessore", name: "Jashore", value: "jessore" },
      { id: "magura", name: "Magura", value: "magura" },
      { id: "jhenaidah", name: "Jhenaidah", value: "jhenaidah" },
      { id: "chuadanga", name: "Chuadanga", value: "chuadanga" },
      { id: "kushtia", name: "Kushtia", value: "kushtia" },
      { id: "meherpur", name: "Meherpur", value: "meherpur" },
      { id: "narail", name: "Narail", value: "narail" },
    ],
    rajshahi: [
      { id: "rajshahi", name: "Rajshahi", value: "rajshahi" },
      { id: "natore", name: "Natore", value: "natore" },
      { id: "pabna", name: "Pabna", value: "pabna" },
      { id: "sirajganj", name: "Sirajganj", value: "sirajganj" },
      { id: "naogaon", name: "Naogaon", value: "naogaon" },
      { id: "chapainawabganj", name: "Chapainawabganj", value: "chapainawabganj" },
      { id: "bogra", name: "Bogura", value: "bogra" },
      { id: "joypurhat", name: "Joypurhat", value: "joypurhat" },
    ],
    barishal: [
      { id: "barishal", name: "Barishal", value: "barishal" },
      { id: "bhola", name: "Bhola", value: "bhola" },
      { id: "jhalokati", name: "Jhalokati", value: "jhalokati" },
      { id: "patuakhali", name: "Patuakhali", value: "patuakhali" },
      { id: "barguna", name: "Barguna", value: "barguna" },
      { id: "pirojpur", name: "Pirojpur", value: "pirojpur" },
    ],
    sylhet: [
      { id: "sylhet", name: "Sylhet", value: "sylhet" },
      { id: "maulvibazar", name: "Moulvibazar", value: "maulvibazar" },
      { id: "habiganj", name: "Habiganj", value: "habiganj" },
      { id: "sunamganj", name: "Sunamganj", value: "sunamganj" },
    ],
    rangpur: [
      { id: "rangpur", name: "Rangpur", value: "rangpur" },
      { id: "dinajpur", name: "Dinajpur", value: "dinajpur" },
      { id: "gaibandha", name: "Gaibandha", value: "gaibandha" },
      { id: "kurigram", name: "Kurigram", value: "kurigram" },
      { id: "lalmonirhat", name: "Lalmonirhat", value: "lalmonirhat" },
      { id: "nilphamari", name: "Nilphamari", value: "nilphamari" },
      { id: "panchagarh", name: "Panchagarh", value: "panchagarh" },
      { id: "thakurgaon", name: "Thakurgaon", value: "thakurgaon" },
    ],
    mymensingh: [
      { id: "mymensingh", name: "Mymensingh", value: "mymensingh" },
      { id: "jamalpur", name: "Jamalpur", value: "jamalpur" },
      { id: "netrokona", name: "Netrokona", value: "netrokona" },
      { id: "sherpur", name: "Sherpur", value: "sherpur" },
    ],
  },

  upazilas: {
    // Dhaka District Upazilas
    dhaka: [
      { id: "dhanmondi", name: "Dhanmondi", value: "dhanmondi" },
      { id: "gulshan", name: "Gulshan", value: "gulshan" },
      { id: "mirpur", name: "Mirpur", value: "mirpur" },
      { id: "pallabi", name: "Pallabi", value: "pallabi" },
      { id: "ramna", name: "Ramna", value: "ramna" },
      { id: "shahbag", name: "Shahbag", value: "shahbag" },
      { id: "sher-e-bangla-nagar", name: "Sher-e-Bangla Nagar", value: "sher-e-bangla-nagar" },
      { id: "tejgaon", name: "Tejgaon", value: "tejgaon" },
      { id: "uttara", name: "Uttara", value: "uttara" },
      { id: "kafrul", name: "Kafrul", value: "kafrul" },
      { id: "biman-bandar", name: "Biman Bandar", value: "biman-bandar" },
      { id: "kadamtali", name: "Kadamtali", value: "kadamtali" },
      { id: "kotwali", name: "Kotwali", value: "kotwali" },
      { id: "lalbagh", name: "Lalbagh", value: "lalbagh" },
      { id: "motijheel", name: "Motijheel", value: "motijheel" },
      { id: "paltan", name: "Paltan", value: "paltan" },
      { id: "ramna", name: "Ramna", value: "ramna" },
      { id: "sabujbagh", name: "Sabujbagh", value: "sabujbagh" },
      { id: "sutrapur", name: "Sutrapur", value: "sutrapur" },
      { id: "khilgaon", name: "Khilgaon", value: "khilgaon" },
      { id: "khilkhet", name: "Khilkhet", value: "khilkhet" },
      { id: "cantonment", name: "Cantonment", value: "cantonment" },
    ],
    gazipur: [
      { id: "gazipur-sadar", name: "Gazipur Sadar", value: "gazipur-sadar" },
      { id: "kaliakair", name: "Kaliakair", value: "kaliakair" },
      { id: "kapasia", name: "Kapasia", value: "kapasia" },
      { id: "sreepur", name: "Sreepur", value: "sreepur" },
      { id: "kaliganj", name: "Kaliganj", value: "kaliganj" },
      { id: "tungi", name: "Tungi", value: "tungi" },
    ],
    narayanganj: [
      { id: "narayanganj-sadar", name: "Narayanganj Sadar", value: "narayanganj-sadar" },
      { id: "sonargaon", name: "Sonargaon", value: "sonargaon" },
      { id: "rupganj", name: "Rupganj", value: "rupganj" },
      { id: "bandar", name: "Bandar", value: "bandar" },
      { id: "araihazar", name: "Araihazar", value: "araihazar" },
    ],
    tangail: [
      { id: "tangail-sadar", name: "Tangail Sadar", value: "tangail-sadar" },
      { id: "kalihati", name: "Kalihati", value: "kalihati" },
      { id: "basail", name: "Basail", value: "basail" },
      { id: "bhuapur", name: "Bhuapur", value: "bhuapur" },
      { id: "delduar", name: "Delduar", value: "delduar" },
      { id: "ghatail", name: "Ghatail", value: "ghatail" },
      { id: "nagarpur", name: "Nagarpur", value: "nagarpur" },
      { id: "mirzapur", name: "Mirzapur", value: "mirzapur" },
      { id: "sakhipur", name: "Sakhipur", value: "sakhipur" },
    ],
    kishoreganj: [
      { id: "kishoreganj-sadar", name: "Kishoreganj Sadar", value: "kishoreganj-sadar" },
      { id: "bhairab", name: "Bhairab", value: "bhairab" },
      { id: "bajitpur", name: "Bajitpur", value: "bajitpur" },
      { id: "katiadi", name: "Katiadi", value: "katiadi" },
      { id: "karimganj", name: "Karimganj", value: "karimganj" },
      { id: "hossainpur", name: "Hossainpur", value: "hossainpur" },
      { id: "tarail", name: "Tarail", value: "tarail" },
      { id: "itna", name: "Itna", value: "itna" },
      { id: "nikli", name: "Nikli", value: "nikli" },
      { id: "pakundia", name: "Pakundia", value: "pakundia" },
    ],
    manikganj: [
      { id: "manikganj-sadar", name: "Manikganj Sadar", value: "manikganj-sadar" },
      { id: "saturia", name: "Saturia", value: "saturia" },
      { id: "shivalaya", name: "Shivalaya", value: "shivalaya" },
      { id: "ghior", name: "Ghior", value: "ghior" },
      { id: "singair", name: "Singair", value: "singair" },
      { id: "daulatpur", name: "Daulatpur", value: "daulatpur" },
      { id: "harirampur", name: "Harirampur", value: "harirampur" },
    ],
    munshiganj: [
      { id: "munshiganj-sadar", name: "Munshiganj Sadar", value: "munshiganj-sadar" },
      { id: "tongibari", name: "Tongibari", value: "tongibari" },
      { id: "sreenagar", name: "Sreenagar", value: "sreenagar" },
      { id: "sirajdikhan", name: "Sirajdikhan", value: "sirajdikhan" },
      { id: "lohajang", name: "Lohajang", value: "lohajang" },
      { id: "gazaria", name: "Gazaria", value: "gazaria" },
    ],
    rajbari: [
      { id: "rajbari-sadar", name: "Rajbari Sadar", value: "rajbari-sadar" },
      { id: "pangsha", name: "Pangsha", value: "pangsha" },
      { id: "baliakandi", name: "Baliakandi", value: "baliakandi" },
      { id: "goalanda", name: "Goalanda", value: "goalanda" },
      { id: "kalukhali", name: "Kalukhali", value: "kalukhali" },
    ],
    shariatpur: [
      { id: "shariatpur-sadar", name: "Shariatpur Sadar", value: "shariatpur-sadar" },
      { id: "damudya", name: "Damudya", value: "damudya" },
      { id: "gosairhat", name: "Gosairhat", value: "gosairhat" },
      { id: "bhedarganj", name: "Bhedarganj", value: "bhedarganj" },
      { id: "jajira", name: "Jajira", value: "jajira" },
      { id: "naria", name: "Naria", value: "naria" },
    ],
    madaripur: [
      { id: "madaripur-sadar", name: "Madaripur Sadar", value: "madaripur-sadar" },
      { id: "shibchar", name: "Shibchar", value: "shibchar" },
      { id: "kalkini", name: "Kalkini", value: "kalkini" },
      { id: "rajoir", name: "Rajoir", value: "rajoir" },
    ],
    gopalganj: [
      { id: "gopalganj-sadar", name: "Gopalganj Sadar", value: "gopalganj-sadar" },
      { id: "muksudpur", name: "Muksudpur", value: "muksudpur" },
      { id: "kashiani", name: "Kashiani", value: "kashiani" },
      { id: "kotalipara", name: "Kotalipara", value: "kotalipara" },
      { id: "tungipara", name: "Tungipara", value: "tungipara" },
    ],
    faridpur: [
      { id: "faridpur-sadar", name: "Faridpur Sadar", value: "faridpur-sadar" },
      { id: "alfadanga", name: "Alfadanga", value: "alfadanga" },
      { id: "boalmari", name: "Boalmari", value: "boalmari" },
      { id: "sadar", name: "Sadarpur", value: "sadar" },
      { id: "bhanga", name: "Bhanga", value: "bhanga" },
      { id: "nagarkanda", name: "Nagarkanda", value: "nagarkanda" },
      { id: "char-bhadrasan", name: "Char Bhadrasan", value: "char-bhadrasan" },
      { id: "madukhali", name: "Madukhali", value: "madukhali" },
      { id: "saltha", name: "Saltha", value: "saltha" },
    ],

    // Chattogram Division Upazilas
    chattogram: [
      { id: "chattogram-sadar", name: "Chattogram Sadar", value: "chattogram-sadar" },
      { id: "patiya", name: "Patiya", value: "patiya" },
      { id: "sitakunda", name: "Sitakunda", value: "sitakunda" },
      { id: "boalkhali", name: "Boalkhali", value: "boalkhali" },
      { id: "anwara", name: "Anwara", value: "anwara" },
      { id: "karnaphuli", name: "Karnaphuli", value: "karnaphuli" },
      { id: "chandanaish", name: "Chandanaish", value: "chandanaish" },
      { id: "satkania", name: "Satkania", value: "satkania" },
      { id: "lohagara", name: "Lohagara", value: "lohagara" },
      { id: "rangunia", name: "Rangunia", value: "rangunia" },
      { id: "raozan", name: "Raozan", value: "raozan" },
      { id: "hathazari", name: "Hathazari", value: "hathazari" },
      { id: "fatikchhari", name: "Fatikchhari", value: "fatikchhari" },
      { id: "mirsharai", name: "Mirsharai", value: "mirsharai" },
      { id: "sandwip", name: "Sandwip", value: "sandwip" },
      { id: "banshkhali", name: "Banshkhali", value: "banshkhali" },
    ],
    "cox-bazar": [
      { id: "cox-bazar-sadar", name: "Cox's Bazar Sadar", value: "cox-bazar-sadar" },
      { id: "teknaf", name: "Teknaf", value: "teknaf" },
      { id: "ukhiya", name: "Ukhiya", value: "ukhiya" },
      { id: "ramu", name: "Ramu", value: "ramu" },
      { id: "chakaria", name: "Chakaria", value: "chakaria" },
      { id: "maheshkhali", name: "Maheshkhali", value: "maheshkhali" },
      { id: "kutubdia", name: "Kutubdia", value: "kutubdia" },
      { id: "pekuya", name: "Pekua", value: "pekuya" },
    ],
    bandarban: [
      { id: "bandarban-sadar", name: "Bandarban Sadar", value: "bandarban-sadar" },
      { id: "lama", name: "Lama", value: "lama" },
      { id: "naikhongchhari", name: "Naikhongchhari", value: "naikhongchhari" },
      { id: "rowangchhari", name: "Rowangchhari", value: "rowangchhari" },
      { id: "rua", name: "Ruma", value: "rua" },
      { id: "thanchi", name: "Thanchi", value: "thanchi" },
      { id: "alikadam", name: "Alikadam", value: "alikadam" },
    ],
    rangamati: [
      { id: "rangamati-sadar", name: "Rangamati Sadar", value: "rangamati-sadar" },
      { id: "belaichhari", name: "Belaichhari", value: "belaichhari" },
      { id: "baghaichhari", name: "Baghaichhari", value: "baghaichhari" },
      { id: "barkal", name: "Barkal", value: "barkal" },
      { id: "juraichhari", name: "Juraichhari", value: "juraichhari" },
      { id: "kaptai", name: "Kaptai", value: "kaptai" },
      { id: "langadu", name: "Langadu", value: "langadu" },
      { id: "nannerchar", name: "Nannerchar", value: "nannerchar" },
      { id: "rajanagar", name: "Rajanagar", value: "rajanagar" },
    ],
    khagrachari: [
      { id: "khagrachari-sadar", name: "Khagrachari Sadar", value: "khagrachari-sadar" },
      { id: "dighinala", name: "Dighinala", value: "dighinala" },
      { id: "panchari", name: "Panchari", value: "panchari" },
      { id: "lakshmichhari", name: "Lakshmichhari", value: "lakshmichhari" },
      { id: "mahalchhari", name: "Mahalchhari", value: "mahalchhari" },
      { id: "manikchhari", name: "Manikchhari", value: "manikchhari" },
      { id: "ramgarh", name: "Ramgarh", value: "ramgarh" },
      { id: "matiranga", name: "Matiranga", value: "matiranga" },
    ],
    feni: [
      { id: "feni-sadar", name: "Feni Sadar", value: "feni-sadar" },
      { id: "chhagalnaiya", name: "Chhagalnaiya", value: "chhagalnaiya" },
      { id: "sonagazi", name: "Sonagazi", value: "sonagazi" },
      { id: "daganbhuiyan", name: "Daganbhuiyan", value: "daganbhuiyan" },
      { id: "parshuram", name: "Parshuram", value: "parshuram" },
      { id: "fulgazi", name: "Fulgazi", value: "fulgazi" },
    ],
    comilla: [
      { id: "comilla-sadar", name: "Cumilla Sadar", value: "comilla-sadar" },
      { id: "laksham", name: "Laksham", value: "laksham" },
      { id: "chandina", name: "Chandina", value: "chandina" },
      { id: "barura", name: "Barura", value: "barura" },
      { id: "burichang", name: "Burichang", value: "burichang" },
      { id: "brammanpara", name: "Brahmanpara", value: "brammanpara" },
      { id: "davidhar", name: "Davidhar", value: "davidhar" },
      { id: "debidwar", name: "Debidwar", value: "debidwar" },
      { id: "homna", name: "Homna", value: "homna" },
      { id: "langalkot", name: "Langalkot", value: "langalkot" },
      { id: "manoharganj", name: "Manoharganj", value: "manoharganj" },
      { id: "meghna", name: "Meghna", value: "meghna" },
      { id: "muradnagar", name: "Muradnagar", value: "muradnagar" },
      { id: "nangalkot", name: "Nangalkot", value: "nangalkot" },
      { id: "titas", name: "Titas", value: "titas" },
    ],
    noakhali: [
      { id: "noakhali-sadar", name: "Noakhali Sadar", value: "noakhali-sadar" },
      { id: "begumganj", name: "Begumganj", value: "begumganj" },
      { id: "chatkhil", name: "Chatkhil", value: "chatkhil" },
      { id: "companiganj", name: "Companiganj", value: "companiganj" },
      { id: "hatiya", name: "Hatiya", value: "hatiya" },
      { id: "kabirhat", name: "Kabirhat", value: "kabirhat" },
      { id: "senbagh", name: "Senbagh", value: "senbagh" },
      { id: "sonaimuri", name: "Sonaimuri", value: "sonaimuri" },
      { id: "subarnachar", name: "Subarnachar", value: "subarnachar" },
    ],
    lakshmipur: [
      { id: "lakshmipur-sadar", name: "Lakshmipur Sadar", value: "lakshmipur-sadar" },
      { id: "raipur", name: "Raipur", value: "raipur" },
      { id: "ramganj", name: "Ramganj", value: "ramganj" },
      { id: "ramgati", name: "Ramgati", value: "ramgati" },
      { id: "kamalnagar", name: "Kamalnagar", value: "kamalnagar" },
    ],
    brahmanbaria: [
      { id: "brahmanbaria-sadar", name: "Brahmanbaria Sadar", value: "brahmanbaria-sadar" },
      { id: "kasba", name: "Kasba", value: "kasba" },
      { id: "nasirnagar", name: "Nasirnagar", value: "nasirnagar" },
      { id: "sarail", name: "Sarail", value: "sarail" },
      { id: "ashuganj", name: "Ashuganj", value: "ashuganj" },
      { id: "akhowra", name: "Akhaura", value: "akhowra" },
      { id: "bancharampur", name: "Bancharampur", value: "bancharampur" },
      { id: "nabinagar", name: "Nabinagar", value: "nabinagar" },
      { id: "bijoynagar", name: "Bijoynagar", value: "bijoynagar" },
    ],
    chandpur: [
      { id: "chandpur-sadar", name: "Chandpur Sadar", value: "chandpur-sadar" },
      { id: "hajiganj", name: "Hajiganj", value: "hajiganj" },
      { id: "faridganj", name: "Faridganj", value: "faridganj" },
      { id: "kachua", name: "Kachua", value: "kachua" },
      { id: "matlab-uttar", name: "Matlab Uttar", value: "matlab-uttar" },
      { id: "matlab-dakshin", name: "Matlab Dakshin", value: "matlab-dakshin" },
      { id: "shahrasti", name: "Shahrasti", value: "shahrasti" },
      { id: "haimchar", name: "Haimchar", value: "haimchar" },
    ],

    // Khulna Division Upazilas
    khulna: [
      { id: "khulna-sadar", name: "Khulna Sadar", value: "khulna-sadar" },
      { id: "dumuria", name: "Dumuria", value: "dumuria" },
      { id: "dacope", name: "Dacope", value: "dacope" },
      { id: "terokhada", name: "Terokhada", value: "terokhada" },
      { id: "phultala", name: "Phultala", value: "phultala" },
      { id: "batiaghata", name: "Batiaghata", value: "batiaghata" },
      { id: "paikgacha", name: "Paikgacha", value: "paikgacha" },
      { id: "koyra", name: "Koyra", value: "koyra" },
      { id: "rupsha", name: "Rupsha", value: "rupsha" },
    ],
    bagerhat: [
      { id: "bagerhat-sadar", name: "Bagerhat Sadar", value: "bagerhat-sadar" },
      { id: "fakirhat", name: "Fakirhat", value: "fakirhat" },
      { id: "mollahat", name: "Mollahat", value: "mollahat" },
      { id: "kachua", name: "Kachua", value: "kachua" },
      { id: "morrelganj", name: "Morrelganj", value: "morrelganj" },
      { id: "rampal", name: "Rampal", value: "rampal" },
      { id: "mongla", name: "Mongla", value: "mongla" },
      { id: "chitalmari", name: "Chitalmari", value: "chitalmari" },
      { id: "sarankhola", name: "Sarankhola", value: "sarankhola" },
    ],
    satkhira: [
      { id: "satkhira-sadar", name: "Satkhira Sadar", value: "satkhira-sadar" },
      { id: "assasuni", name: "Assasuni", value: "assasuni" },
      { id: "debata", name: "Debhata", value: "debata" },
      { id: "tala", name: "Tala", value: "tala" },
      { id: "kalaroa", name: "Kalaroa", value: "kalaroa" },
      { id: "kaliganj", name: "Kaliganj", value: "kaliganj" },
      { id: "shyamnagar", name: "Shyamnagar", value: "shyamnagar" },
      { id: "patkelghata", name: "Patkelghata", value: "patkelghata" },
    ],
    jessore: [
      { id: "jessore-sadar", name: "Jashore Sadar", value: "jessore-sadar" },
      { id: "manirampur", name: "Manirampur", value: "manirampur" },
      { id: "abhaynagar", name: "Abhaynagar", value: "abhaynagar" },
      { id: "bagherpara", name: "Bagherpara", value: "bagherpara" },
      { id: "chougachha", name: "Chougachha", value: "chougachha" },
      { id: "keshabpur", name: "Keshabpur", value: "keshabpur" },
      { id: "jhikargacha", name: "Jhikargacha", value: "jhikargacha" },
      { id: "sharsha", name: "Sharsha", value: "sharsha" },
    ],
    magura: [
      { id: "magura-sadar", name: "Magura Sadar", value: "magura-sadar" },
      { id: "shalikha", name: "Shalikha", value: "shalikha" },
      { id: "sreepur", name: "Sreepur", value: "sreepur" },
      { id: "mohammadpur", name: "Mohammadpur", value: "mohammadpur" },
    ],
    jhenaidah: [
      { id: "jhenaidah-sadar", name: "Jhenaidah Sadar", value: "jhenaidah-sadar" },
      { id: "kaliganj", name: "Kaliganj", value: "kaliganj" },
      { id: "kotchandpur", name: "Kotchandpur", value: "kotchandpur" },
      { id: "shailkupa", name: "Shailkupa", value: "shailkupa" },
      { id: "harinakundu", name: "Harinakundu", value: "harinakundu" },
      { id: "maheshpur", name: "Maheshpur", value: "maheshpur" },
    ],
    chuadanga: [
      { id: "chuadanga-sadar", name: "Chuadanga Sadar", value: "chuadanga-sadar" },
      { id: "alamdanga", name: "Alamdanga", value: "alamdanga" },
      { id: "damurhuda", name: "Damurhuda", value: "damurhuda" },
      { id: "jibannagar", name: "Jibannagar", value: "jibannagar" },
    ],
    kushtia: [
      { id: "kushtia-sadar", name: "Kushtia Sadar", value: "kushtia-sadar" },
      { id: "kumarkhali", name: "Kumarkhali", value: "kumarkhali" },
      { id: "khoksa", name: "Khoksa", value: "khoksa" },
      { id: "mirpur", name: "Mirpur", value: "mirpur" },
      { id: "daulatpur", name: "Daulatpur", value: "daulatpur" },
      { id: "bheramara", name: "Bheramara", value: "bheramara" },
    ],
    meherpur: [
      { id: "meherpur-sadar", name: "Meherpur Sadar", value: "meherpur-sadar" },
      { id: "gangni", name: "Gangni", value: "gangni" },
      { id: "mujibnagar", name: "Mujibnagar", value: "mujibnagar" },
    ],
    narail: [
      { id: "narail-sadar", name: "Narail Sadar", value: "narail-sadar" },
      { id: "lohagara", name: "Lohagara", value: "lohagara" },
      { id: "kalia", name: "Kalia", value: "kalia" },
    ],

    // Rajshahi Division Upazilas
    rajshahi: [
      { id: "rajshahi-sadar", name: "Rajshahi Sadar", value: "rajshahi-sadar" },
      { id: "paba", name: "Paba", value: "paba" },
      { id: "godagari", name: "Godagari", value: "godagari" },
      { id: "tanore", name: "Tanore", value: "tanore" },
      { id: "bagmara", name: "Bagmara", value: "bagmara" },
      { id: "mohanpur", name: "Mohanpur", value: "mohanpur" },
      { id: "charghat", name: "Charghat", value: "charghat" },
      { id: "puthia", name: "Puthia", value: "puthia" },
      { id: "duorgapur", name: "Durgapur", value: "duorgapur" },
    ],
    natore: [
      { id: "natore-sadar", name: "Natore Sadar", value: "natore-sadar" },
      { id: "bagatipara", name: "Bagatipara", value: "bagatipara" },
      { id: "baraigram", name: "Baraigram", value: "baraigram" },
      { id: "gurudaspur", name: "Gurudaspur", value: "gurudaspur" },
      { id: "lalpur", name: "Lalpur", value: "lalpur" },
      { id: "noldanga", name: "Naldanga", value: "noldanga" },
      { id: "singra", name: "Singra", value: "singra" },
    ],
    pabna: [
      { id: "pabna-sadar", name: "Pabna Sadar", value: "pabna-sadar" },
      { id: "bera", name: "Bera", value: "bera" },
      { id: "bhangura", name: "Bhangura", value: "bhangura" },
      { id: "chatmohar", name: "Chatmohar", value: "chatmohar" },
      { id: "faridpur", name: "Faridpur", value: "faridpur" },
      { id: "ishwardi", name: "Ishwardi", value: "ishwardi" },
      { id: "sujanagar", name: "Sujanagar", value: "sujanagar" },
      { id: "santhia", name: "Santhia", value: "santhia" },
      { id: "atgharia", name: "Atgharia", value: "atgharia" },
    ],
    sirajganj: [
      { id: "sirajganj-sadar", name: "Sirajganj Sadar", value: "sirajganj-sadar" },
      { id: "belkuchi", name: "Belkuchi", value: "belkuchi" },
      { id: "chauhali", name: "Chauhali", value: "chauhali" },
      { id: "kamarkhanda", name: "Kamarkhanda", value: "kamarkhanda" },
      { id: "kazipur", name: "Kazipur", value: "kazipur" },
      { id: "raiganj", name: "Raiganj", value: "raiganj" },
      { id: "shahjadpur", name: "Shahjadpur", value: "shahjadpur" },
      { id: "tarash", name: "Tarash", value: "tarash" },
      { id: "ullapara", name: "Ullapara", value: "ullapara" },
    ],
    naogaon: [
      { id: "naogaon-sadar", name: "Naogaon Sadar", value: "naogaon-sadar" },
      { id: "manda", name: "Manda", value: "manda" },
      { id: "niamatpur", name: "Niamatpur", value: "niamatpur" },
      { id: "patnitala", name: "Patnitala", value: "patnitala" },
      { id: "porsha", name: "Porsha", value: "porsha" },
      { id: "sapahar", name: "Sapahar", value: "sapahar" },
      { id: "dhamoirhat", name: "Dhamoirhat", value: "dhamoirhat" },
      { id: "badalgachhi", name: "Badalgachhi", value: "badalgachhi" },
      { id: "mohadevpur", name: "Mohadevpur", value: "mohadevpur" },
      { id: "raninagar", name: "Raninagar", value: "raninagar" },
    ],
    "chapainawabganj": [
      { id: "chapainawabganj-sadar", name: "Chapainawabganj Sadar", value: "chapainawabganj-sadar" },
      { id: "gomastapur", name: "Gomastapur", value: "gomastapur" },
      { id: "nachol", name: "Nachol", value: "nachol" },
      { id: "bholahat", name: "Bholahat", value: "bholahat" },
      { id: "shibganj", name: "Shibganj", value: "shibganj" },
    ],
    bogra: [
      { id: "bogra-sadar", name: "Bogura Sadar", value: "bogra-sadar" },
      { id: "adamdighi", name: "Adamdighi", value: "adamdighi" },
      { id: "dhunot", name: "Dhunot", value: "dhunot" },
      { id: "dupchanchia", name: "Dupchanchia", value: "dupchanchia" },
      { id: "gabtali", name: "Gabtali", value: "gabtali" },
      { id: "kahaloo", name: "Kahaloo", value: "kahaloo" },
      { id: "nandigram", name: "Nandigram", value: "nandigram" },
      { id: "sariakandi", name: "Sariakandi", value: "sariakandi" },
      { id: "shajahanpur", name: "Shajahanpur", value: "shajahanpur" },
      { id: "sherpur", name: "Sherpur", value: "sherpur" },
      { id: "sonatola", name: "Sonatola", value: "sonatola" },
    ],
    joypurhat: [
      { id: "joypurhat-sadar", name: "Joypurhat Sadar", value: "joypurhat-sadar" },
      { id: "akkela", name: "Akkelpur", value: "akkela" },
      { id: "kalai", name: "Kalai", value: "kalai" },
      { id: "khetlal", name: "Khetlal", value: "khetlal" },
      { id: "panchbibi", name: "Panchbibi", value: "panchbibi" },
    ],

    // Barishal Division Upazilas
    barishal: [
      { id: "barishal-sadar", name: "Barishal Sadar", value: "barishal-sadar" },
      { id: "bakerganj", name: "Bakerganj", value: "bakerganj" },
      { id: "banaripara", name: "Banaripara", value: "banaripara" },
      { id: "gaurnadi", name: "Gaurnadi", value: "gaurnadi" },
      { id: "hizla", name: "Hizla", value: "hizla" },
      { id: "mehendiganj", name: "Mehendiganj", value: "mehendiganj" },
      { id: "muladi", name: "Muladi", value: "muladi" },
      { id: "wazirpur", name: "Wazirpur", value: "wazirpur" },
      { id: "agailjhara", name: "Agailjhara", value: "agailjhara" },
      { id: "babuganj", name: "Babuganj", value: "babuganj" },
    ],
    bhola: [
      { id: "bhola-sadar", name: "Bhola Sadar", value: "bhola-sadar" },
      { id: "burhanuddin", name: "Burhanuddin", value: "burhanuddin" },
      { id: "char-fasson", name: "Char Fasson", value: "char-fasson" },
      { id: "daulatkhan", name: "Daulatkhan", value: "daulatkhan" },
      { id: "lalmohan", name: "Lalmohan", value: "lalmohan" },
      { id: "manpura", name: "Manpura", value: "manpura" },
      { id: "tazumuddin", name: "Tazumuddin", value: "tazumuddin" },
    ],
    jhalokati: [
      { id: "jhalokati-sadar", name: "Jhalokati Sadar", value: "jhalokati-sadar" },
      { id: "kathalia", name: "Kathalia", value: "kathalia" },
      { id: "nalchity", name: "Nalchity", value: "nalchity" },
      { id: "rajapur", name: "Rajapur", value: "rajapur" },
    ],
    patuakhali: [
      { id: "patuakhali-sadar", name: "Patuakhali Sadar", value: "patuakhali-sadar" },
      { id: "baufal", name: "Baufal", value: "baufal" },
      { id: "dumki", name: "Dumki", value: "dumki" },
      { id: "galachipa", name: "Galachipa", value: "galachipa" },
      { id: "kalapara", name: "Kalapara", value: "kalapara" },
      { id: "mirzaganj", name: "Mirzaganj", value: "mirzaganj" },
      { id: "rangabali", name: "Rangabali", value: "rangabali" },
      { id: "dasmina", name: "Dashmina", value: "dasmina" },
    ],
    barguna: [
      { id: "barguna-sadar", name: "Barguna Sadar", value: "barguna-sadar" },
      { id: "amtali", name: "Amtali", value: "amtali" },
      { id: "bamna", name: "Bamna", value: "bamna" },
      { id: "betagi", name: "Betagi", value: "betagi" },
      { id: "patharghata", name: "Patharghata", value: "patharghata" },
      { id: "taltali", name: "Taltali", value: "taltali" },
    ],
    pirojpur: [
      { id: "pirojpur-sadar", name: "Pirojpur Sadar", value: "pirojpur-sadar" },
      { id: "bhandaria", name: "Bhandaria", value: "bhandaria" },
      { id: "kawkhali", name: "Kawkhali", value: "kawkhali" },
      { id: "mathbaria", name: "Mathbaria", value: "mathbaria" },
      { id: "nazirpur", name: "Nazirpur", value: "nazirpur" },
      { id: "nesarabad", name: "Nesarabad", value: "nesarabad" },
      { id: "indurkani", name: "Indurkani", value: "indurkani" },
    ],

    // Sylhet Division Upazilas
    sylhet: [
      { id: "sylhet-sadar", name: "Sylhet Sadar", value: "sylhet-sadar" },
      { id: "beanibazar", name: "Beanibazar", value: "beanibazar" },
      { id: "golapganj", name: "Golapganj", value: "golapganj" },
      { id: "jakiganj", name: "Jakiganj", value: "jakiganj" },
      { id: "kanaighat", name: "Kanaighat", value: "kanaighat" },
      { id: "kompaniganj", name: "Kompaniganj", value: "kompaniganj" },
      { id: "osmani-nagar", name: "Osmani Nagar", value: "osmani-nagar" },
      { id: "fenchuganj", name: "Fenchuganj", value: "fenchuganj" },
      { id: "bishwanath", name: "Bishwanath", value: "bishwanath" },
      { id: "balaganj", name: "Balaganj", value: "balaganj" },
      { id: "zokiganj", name: "Zokiganj", value: "zokiganj" },
      { id: "gowainghat", name: "Gowainghat", value: "gowainghat" },
    ],
    maulvibazar: [
      { id: "maulvibazar-sadar", name: "Moulvibazar Sadar", value: "maulvibazar-sadar" },
      { id: "barlekha", name: "Barlekha", value: "barlekha" },
      { id: "juri", name: "Juri", value: "juri" },
      { id: "kamalganj", name: "Kamalganj", value: "kamalganj" },
      { id: "kulaura", name: "Kulaura", value: "kulaura" },
      { id: "sreemangal", name: "Sreemangal", value: "sreemangal" },
      { id: "rajnagar", name: "Rajnagar", value: "rajnagar" },
    ],
    habiganj: [
      { id: "habiganj-sadar", name: "Habiganj Sadar", value: "habiganj-sadar" },
      { id: "ajmiriganj", name: "Ajmiriganj", value: "ajmiriganj" },
      { id: "baniachang", name: "Baniachang", value: "baniachang" },
      { id: "bahubal", name: "Bahubal", value: "bahubal" },
      { id: "chunarughat", name: "Chunarughat", value: "chunarughat" },
      { id: "lakhai", name: "Lakhai", value: "lakhai" },
      { id: "madhabpur", name: "Madhabpur", value: "madhabpur" },
      { id: "nabiganj", name: "Nabiganj", value: "nabiganj" },
      { id: "shayestaganj", name: "Shayestaganj", value: "shayestaganj" },
    ],
    sunamganj: [
      { id: "sunamganj-sadar", name: "Sunamganj Sadar", value: "sunamganj-sadar" },
      { id: "bishwamvarpur", name: "Bishwamvarpur", value: "bishwamvarpur" },
      { id: "chhatak", name: "Chhatak", value: "chhatak" },
      { id: "derai", name: "Derai", value: "derai" },
      { id: "dharampasha", name: "Dharampasha", value: "dharampasha" },
      { id: "dowarabazar", name: "Dowarabazar", value: "dowarabazar" },
      { id: "jamalganj", name: "Jamalganj", value: "jamalganj" },
      { id: "shalla", name: "Shalla", value: "shalla" },
      { id: "tahirpur", name: "Tahirpur", value: "tahirpur" },
      { id: "duarabazar", name: "Duarabazar", value: "duarabazar" },
    ],

    // Rangpur Division Upazilas
    rangpur: [
      { id: "rangpur-sadar", name: "Rangpur Sadar", value: "rangpur-sadar" },
      { id: "badarganj", name: "Badarganj", value: "badarganj" },
      { id: "gangachara", name: "Gangachara", value: "gangachara" },
      { id: "kaunia", name: "Kaunia", value: "kaunia" },
      { id: "mithapukur", name: "Mithapukur", value: "mithapukur" },
      { id: "pirganj", name: "Pirganj", value: "pirganj" },
      { id: "taraganj", name: "Taraganj", value: "taraganj" },
    ],
    dinajpur: [
      { id: "dinajpur-sadar", name: "Dinajpur Sadar", value: "dinajpur-sadar" },
      { id: "birganj", name: "Birganj", value: "birganj" },
      { id: "birampur", name: "Birampur", value: "birampur" },
      { id: "biral", name: "Biral", value: "biral" },
      { id: "bochaganj", name: "Bochaganj", value: "bochaganj" },
      { id: "chirirbandar", name: "Chirirbandar", value: "chirirbandar" },
      { id: "fulbari", name: "Fulbari", value: "fulbari" },
      { id: "ghoraghat", name: "Ghoraghat", value: "ghoraghat" },
      { id: "hakimpur", name: "Hakimpur", value: "hakimpur" },
      { id: "kaharole", name: "Kaharole", value: "kaharole" },
      { id: "khansama", name: "Khansama", value: "khansama" },
      { id: "nawabganj", name: "Nawabganj", value: "nawabganj" },
      { id: "parbatipur", name: "Parbatipur", value: "parbatipur" },
    ],
    gaibandha: [
      { id: "gaibandha-sadar", name: "Gaibandha Sadar", value: "gaibandha-sadar" },
      { id: "fulchhari", name: "Fulchhari", value: "fulchhari" },
      { id: "gobindaganj", name: "Gobindaganj", value: "gobindaganj" },
      { id: "palashbari", name: "Palashbari", value: "palashbari" },
      { id: "sadullapur", name: "Sadullapur", value: "sadullapur" },
      { id: "saghata", name: "Saghata", value: "saghata" },
      { id: "sundarganj", name: "Sundarganj", value: "sundarganj" },
    ],
    kurigram: [
      { id: "kurigram-sadar", name: "Kurigram Sadar", value: "kurigram-sadar" },
      { id: "bhurungamari", name: "Bhurungamari", value: "bhurungamari" },
      { id: "char-rajibpur", name: "Char Rajibpur", value: "char-rajibpur" },
      { id: "chilmari", name: "Chilmari", value: "chilmari" },
      { id: "phulbari", name: "Phulbari", value: "phulbari" },
      { id: "nageshwari", name: "Nageshwari", value: "nageshwari" },
      { id: "rajarhat", name: "Rajarhat", value: "rajarhat" },
      { id: "raomari", name: "Raomari", value: "raomari" },
      { id: "ulipur", name: "Ulipur", value: "ulipur" },
    ],
    lalmonirhat: [
      { id: "lalmonirhat-sadar", name: "Lalmonirhat Sadar", value: "lalmonirhat-sadar" },
      { id: "aditmari", name: "Aditmari", value: "aditmari" },
      { id: "hatibandha", name: "Hatibandha", value: "hatibandha" },
      { id: "kaliganj", name: "Kaliganj", value: "kaliganj" },
      { id: "patgram", name: "Patgram", value: "patgram" },
    ],
    nilphamari: [
      { id: "nilphamari-sadar", name: "Nilphamari Sadar", value: "nilphamari-sadar" },
      { id: "domar", name: "Domar", value: "domar" },
      { id: "jaldhaka", name: "Jaldhaka", value: "jaldhaka" },
      { id: "kishoreganj", name: "Kishoreganj", value: "kishoreganj" },
      { id: "saidpur", name: "Saidpur", value: "saidpur" },
      { id: "dimla", name: "Dimla", value: "dimla" },
    ],
    panchagarh: [
      { id: "panchagarh-sadar", name: "Panchagarh Sadar", value: "panchagarh-sadar" },
      { id: "atikchhari", name: "Atwari", value: "atikchhari" },
      { id: "boda", name: "Boda", value: "boda" },
      { id: "debiganj", name: "Debiganj", value: "debiganj" },
      { id: "tetulia", name: "Tetulia", value: "tetulia" },
    ],
    thakurgaon: [
      { id: "thakurgaon-sadar", name: "Thakurgaon Sadar", value: "thakurgaon-sadar" },
      { id: "balia-dangi", name: "Baliadangi", value: "balia-dangi" },
      { id: "haripur", name: "Haripur", value: "haripur" },
      { id: "pirganj", name: "Pirganj", value: "pirganj" },
      { id: "ranisankail", name: "Ranisankail", value: "ranisankail" },
    ],

    // Mymensingh Division Upazilas
    mymensingh: [
      { id: "mymensingh-sadar", name: "Mymensingh Sadar", value: "mymensingh-sadar" },
      { id: "bhaluka", name: "Bhaluka", value: "bhaluka" },
      { id: "fulbaria", name: "Fulbaria", value: "fulbaria" },
      { id: "gaffargaon", name: "Gaffargaon", value: "gaffargaon" },
      { id: "haluaghat", name: "Haluaghat", value: "haluaghat" },
      { id: "ishwarganj", name: "Ishwarganj", value: "ishwarganj" },
      { id: "muktagacha", name: "Muktagacha", value: "muktagacha" },
      { id: "nandail", name: "Nandail", value: "nandail" },
      { id: "phulpur", name: "Phulpur", value: "phulpur" },
      { id: "trishal", name: "Trishal", value: "trishal" },
      { id: "tarakanda", name: "Tarakanda", value: "tarakanda" },
      { id: "gouripur", name: "Gouripur", value: "gouripur" },
    ],
    jamalpur: [
      { id: "jamalpur-sadar", name: "Jamalpur Sadar", value: "jamalpur-sadar" },
      { id: "bakshiganj", name: "Bakshiganj", value: "bakshiganj" },
      { id: "dewanaganj", name: "Dewanganj", value: "dewanaganj" },
      { id: "islamganj", name: "Islamganj", value: "islamganj" },
      { id: "madarganj", name: "Madarganj", value: "madarganj" },
      { id: "melandaha", name: "Melandaha", value: "melandaha" },
      { id: "sarishabari", name: "Sarishabari", value: "sarishabari" },
    ],
    netrokona: [
      { id: "netrokona-sadar", name: "Netrokona Sadar", value: "netrokona-sadar" },
      { id: "atpara", name: "Atpara", value: "atpara" },
      { id: "barhatta", name: "Barhatta", value: "barhatta" },
      { id: "durgapur", name: "Durgapur", value: "durgapur" },
      { id: "kalmakanda", name: "Kalmakanda", value: "kalmakanda" },
      { id: "kendua", name: "Kendua", value: "kendua" },
      { id: "khaliajuri", name: "Khaliajuri", value: "khaliajuri" },
      { id: "madan", name: "Madan", value: "madan" },
      { id: "mohanganj", name: "Mohanganj", value: "mohanganj" },
      { id: "purbadhala", name: "Purbadhala", value: "purbadhala" },
    ],
    sherpur: [
      { id: "sherpur-sadar", name: "Sherpur Sadar", value: "sherpur-sadar" },
      { id: "jhenaigati", name: "Jhenaigati", value: "jhenaigati" },
      { id: "nakla", name: "Nakla", value: "nakla" },
      { id: "nalitabari", name: "Nalitabari", value: "nalitabari" },
      { id: "sreebardi", name: "Sreebardi", value: "sreebardi" },
    ],
  },
};